my_project_rel_1/login_app/urls.py
# from django.urls import path
# from .views import login_page, newuser_page, home_page, login_verification, add_newuser
#
# urlpatterns = [
#     path('',login_page),
#     path('newuser/', newuser_page),
#     path('home/', home_page),
#     path('post/', login_verification),
#     path('add_newuser/',add_newuser)
#
# ]
# login_app/urls.py

from django.urls import path
from .views import login_page, newuser_page, home_page, login_verification, add_newuser

app_name = 'login_app'  # Add this line to define the app's namespace

urlpatterns = [
    path('', login_page, name='login_page'),
    path('newuser/', newuser_page, name='newuser_page'),
    path('home/', home_page, name='home_page'),
    path('post/', login_verification, name='login_verification'),
    path('add_newuser/', add_newuser, name='add_newuser'),
]

my_project_rel_1/my_project_rel_1/urls.py
"""
my_project_rel_1/urls
"""
from django.contrib import admin
from django.urls import path, include
import cartapp.urls
import pns.urls
import homeapp.urls
import login_app.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(homeapp.urls)),
    path('cart/', include(cartapp.urls)),
    path('login/', include(login_app.urls)),
    path('pns/', include(pns.urls)),
]

# http://127.0.0.1:8000/cartapp/

my_project_rel_1/pns/urls.py
from django.urls import path
from .views import products_page, save_cart


urlpatterns = [
    path('products/', products_page),
    path('products/save_cart/', save_cart)

]

my_project_rel_1/login_app/models.py
"""
login_app/models.py
"""

# from django.contrib.auth.models import AbstractUser
from django.db import models

class CredentialsTable(models.Model):
    # You can add custom fields or methods here if needed
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=120)
    email = models.EmailField(max_length=100)
    mobile = models.DecimalField(max_digits=10, decimal_places=0)
    country = models.CharField(max_length=15)

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'credentials_table'

my_project_rel_1/login_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import CredentialsTable

# Create your views here.
def login_page(request):
    return render(request, 'index.html', {})

def newuser_page(request):
    return render(request, 'newuser.html', {})


def home_page(request):
    return render(request, 'home.html', {})

def login_verification(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user_exist = CredentialsTable.objects.filter(username= username, password=password).exists()
        print(request.POST)

        if user_exist:
            user_id = CredentialsTable.objects.filter(username= username)[0].user_id
            request.session['user_id']=user_id
            return redirect('/pns/products')

        else:
            error_message = 'Invalid credentials. Please try again.'
            return render(request, 'index.html', {'error_message': error_message})


def add_newuser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        mobile = request.POST.get('mobile')
        country = request.POST.get('country')
        password = request.POST.get('password')

        new_user = CredentialsTable()
        new_user.username = username
        new_user.email = email
        new_user.mobile = mobile
        new_user.country = country
        new_user.password = password

        new_user.save()

        return redirect('/login')

    else:
        return HttpResponse("Not received")

my_project_rel_1/login_app/templates/base_template.html
<!DOCTYPE html>
<html lang="en" >
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Login Page with Username and Password Example</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/login_style.css' %}">
    {% block ordercss %}
    {% endblock %}

</head>
<body>
<!-- Navigation bar -->
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
      <img src="{% static 'image/logo-image.png' %}" width="50px" height="50px">
  </a>
  <button class="navbar-toggler " id="nav-border" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/login/">Login and Signup</a>
      <a class="nav-item nav-link" href="/pns/products/">Catalog and Services</a>
      <a class="nav-item nav-link " href="/cart/">Shopping Cart and Checkout</a>
    </div>
  </div>
</nav>

{% block mycontent %}

{% endblock %}



<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

my_project_rel_1/login_app/templates/basetemplate.html
<!DOCTYPE html>
<html lang="en" >
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Login Page with Username and Password Example</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/login_style.css' %}">

</head>
<body>
<!-- Navigation bar -->
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
      <img src="{% static 'image/logo-image.png' %}" width="50px" height="50px">
  </a>
  <button class="navbar-toggler " id="nav-border" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
<a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="/login/">Login and Signup</a>
      <a class="nav-item nav-link" href="/pns/products/">Catalog and Services</a>
      <a class="nav-item nav-link " href="/cart/">Shopping Cart and Checkout</a>
    </div>
  </div>
</nav>

{% block mycontent %}

{% endblock %}



<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

my_project_rel_1/login_app/templates/home.html
{% extends 'basetemplate.html' %}
{% load static %}


{% block mycontent %}
<!-- Full-width welcome text -->
<div class="welcome-text">
    <h2 class="display-3">Welcome to NRICARGO</h2>
</div>


<!-- Grey background color for content -->
<div class="container-fluid grey-background">
    <div class="center-box">
        <div class="box">
            <p class="lead">Explore our NRI Cargo services for secure and efficient shipments to and from abroad. We understand the importance of timely and reliable cargo services for NRIs (Non-Resident Indians).</p>
            <p class="lead">Our NRI Cargo services include:</p>
            <ul class="lead">
                <li>Door-to-door delivery</li>
                <li>Customs clearance assistance</li>
                <li>Secure packaging for fragile items</li>
                <li>Tracking and updates for your shipment</li>
            </ul>
            <p class="lead">Whether you are sending important documents, gifts, or personal belongings, trust us for a hassle-free NRI cargo experience.</p>
        </div>

        <div class="contact-box">
            <p class="lead">Contact us for more information:</p>
            <ul class="lead">
                <li>Email: info@nricargo.com</li>
                <li>Phone: +123-456-7890</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

my_project_rel_1/login_app/templates/index.html
{% extends 'basetemplate.html' %}

{% block mycontent %}
{% load static %}
<div class="align div-form div-form-1">

  <div class="grid">

    <form action="/login/post/" method="POST" class="form login">
      <h2>User login</h2>
      {% csrf_token %}
      <div class="form__field">
        <label for="login__username"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use></svg><span class="hidden">Username</span></label>
        <input id="login__username" type="text" name="username" class="form__input" placeholder="Username" required>
      </div>

      <div class="form__field">
        <label for="login__password"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#lock"></use></svg><span class="hidden">Password</span></label>
        <input id="login__password" type="password" name="password" class="form__input" placeholder="Password" required>
      </div>

      <div class="form__field">
        <input type="submit" value="Sign In">
      </div>

    </form>

    {% if error_message %}
      <div class="alert alert-danger" id="alert-message" style="margin-top: 1.5rem !important;">
         {{ error_message }}
      </div>
    {% endif %}

    <p class="text--center">Not a member? <a href="/login/newuser/">Sign up now</a> <svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="{% static 'path/to/icons.svg#arrow-right' %}"></use>
    </svg></p>
  </div>

  <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z"/></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z"/></symbol></svg>

</div>

<script>
  // Add JavaScript to hide the alert after page reload
  window.onload = function() {

    var alertMessage = document.getElementById('alert-message');
    if (alertMessage) {
      setTimeout(function() {
        alertMessage.style.display = 'none';
      }, 3000);  // Set the time in milliseconds (5 seconds in this example)
    }
  };
</script>

{% endblock %}

my_project_rel_1/login_app/templates/newuser.html
{% extends 'basetemplate.html' %}

{% block mycontent %}
{% load static %}
<div class="align div-form">

  <div class="grid">

    <form action="{% url 'login_app:add_newuser' %}" method="POST" class="form login" id="registration-form">
      {% csrf_token %}
      <h2>Create new user account</h2>
      <div class="form__field">
        <label for="login_username"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use></svg><span class="hidden">Set username</span></label>
        <input id="login_username" type="text" name="username" class="form_input" placeholder="Set username" required>
      </div>

      <div class="form__field">
        <label for="login_email">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
            <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414zM0 4.697v7.104l5.803-3.558zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586zm3.436-.586L16 11.801V4.697z"/>
          </svg>
        </label>
        <input id="login_email" type="email" name="email" class="form_input" placeholder="Email" required>
    </div>

     <div class="form__field">
        <label for="login_mobile">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
            </svg>
        </label>
        <input id="login_mobile" type="tel" name="mobile" class="form_input" placeholder="Mobile Number" required>
    </div>


      <div class="form__field">
        <label for="login_country">
           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-globe-asia-australia" viewBox="0 0 16 16">
              <path d="m10.495 6.92 1.278-.619a.483.483 0 0 0 .126-.782c-.252-.244-.682-.139-.932.107-.23.226-.513.373-.816.53l-.102.054c-.338.178-.264.626.1.736a.48.48 0 0 0 .346-.027ZM7.741 9.808V9.78a.413.413 0 1 1 .783.183l-.22.443a.6.6 0 0 1-.12.167l-.193.185a.36.36 0 1 1-.5-.516l.112-.108a.45.45 0 0 0 .138-.326M5.672 12.5l.482.233A.386.386 0 1 0 6.32 12h-.416a.7.7 0 0 1-.419-.139l-.277-.206a.302.302 0 1 0-.298.52z"/>
              <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0M1.612 10.867l.756-1.288a1 1 0 0 1 1.545-.225l1.074 1.005a.986.986 0 0 0 1.36-.011l.038-.037a.88.88 0 0 0 .26-.755c-.075-.548.37-1.033.92-1.099.728-.086 1.587-.324 1.728-.957.086-.386-.114-.83-.361-1.2-.207-.312 0-.8.374-.8.123 0 .24-.055.318-.15l.393-.474c.196-.237.491-.368.797-.403.554-.064 1.407-.277 1.583-.973.098-.391-.192-.634-.484-.88-.254-.212-.51-.426-.515-.741a7 7 0 0 1 3.425 7.692 1 1 0 0 0-.087-.063l-.316-.204a1 1 0 0 0-.977-.06l-.169.082a1 1 0 0 1-.741.051l-1.021-.329A1 1 0 0 0 11.205 9h-.165a1 1 0 0 0-.945.674l-.172.499a1 1 0 0 1-.404.514l-.802.518a1 1 0 0 0-.458.84v.455a1 1 0 0 0 1 1h.257a1 1 0 0 1 .542.16l.762.49a1 1 0 0 0 .283.126 7 7 0 0 1-9.49-3.409Z"/>
            </svg>
        </label>
        <select id="login_country" name="country" class="form_input" required>
            <option value="" selected disabled>Select Country</option>
            <option value="United States">United States</option>
            <option value="Canada">Canada</option>
            <option value="Australia">Australia</option>

             <!-- Add more country options as needed -->
        </select>
    </div>

      <div class="form__field">
        <label for="login_password"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#lock"></use></svg><span class="hidden">New password</span></label>
        <input id="login_password" type="password" name="password" class="form_input" placeholder="New password" required>
      </div>

      <div class="form__field">
        <label for="login_confirm_password"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#lock"></use></svg><span class="hidden">Confirm password</span></label>
        <input id="login_confirm_password" type="password" name="confirm_password" class="form_input confirm_password" placeholder="Confirm password" required>

        <i class="fas fa-check-circle green-tick" style="font-size:24px; color:green;"></i>
        <i class="fas fa-close red-cross" style="font-size:24px; color: red;"></i>
      </div>

      <div class="form__field">
        <input type="submit" value="Register" disabled id="register_btn">
      </div>

    </form>

    <div class="alert alert-success  alert-msg" id="registration-success-message"  style="display: none;">
            <strong>Success!</strong> User registered successfully!
    </div>
  </div>
</div>

  <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z"/></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z"/></symbol>></svg>
<script>

      document.getElementById('registration-form').addEventListener('submit', function (event) {
        // Prevent the default form submission
        event.preventDefault();

        // Display the success message
        document.getElementById('registration-success-message').style.display = 'block';

        // Disable the submit button
        document.getElementById("register_btn").disabled = true;

        // Submit the form after a delay (adjust the delay as needed)
        setTimeout(function () {
            document.getElementById('registration-form').submit();
        }, 2000);  // Submit the form after 2 seconds (2000 milliseconds)
    });


    console.log("Hello")
    const passwordInput = document.getElementById('login_password');
    const confirmPasswordInput = document.getElementById('login_confirm_password');

    confirmPasswordInput.addEventListener('input', function() {
        const password = passwordInput.value;
        const confirmPassword = confirmPasswordInput.value;
        console.log(typeof(confirmPassword))


        // Checking if passwords match
        if (password === confirmPassword && confirmPassword!="") {
          console.log('Passwords match!');
          document.getElementById('login_confirm_password').style.borderRadius="0rem"
          document.querySelector('.fas.red-cross').style.display="none"
          document.querySelector('.fas.green-tick').style.display="inline-block"
          document.getElementById("register_btn").disabled=false

        } else {
            document.getElementById("register_btn").disabled=true
            document.querySelector('.fas.green-tick').style.display="none"

            if (confirmPassword == ""){
                document.getElementById('login_confirm_password').style.borderRadius="0rem"
                document.querySelector('.fas.red-cross').style.display="none"

            }
            else{
                console.log('Passwords do not match');
                document.querySelector('.fas.red-cross').style.display="inline-block"

            }

        }
      });

</script>

{% endblock %}

my_project_rel_1/login_app/templates/orderplaced.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Placed</title>
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
</head>
<style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Order Placed</h1>
        <p>We received your purchase request;<br/> we'll be in touch shortly!</p>
      </div>
    </body>
</html>